name: XReplayMinio
version: '${project.version}'
main: re.imc.xreplayminio.XReplayMinio
commands:
  replayminio:
    aliases:
      - replayload
  replaydatafix:
    permission: replay.data.fix
loadbefore:
  - ReplaySystem
depend:
  - XReplayExtendAPI